/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define s1ap_maxPrivateIEs (65535)
#define s1ap_maxProtocolExtensions (65535)
#define s1ap_maxProtocolIEs (65535)
#define s1ap_maxNrOfCSGs (256)
#define s1ap_maxNrOfE_RABs (256)
#define s1ap_maxnoofTAIs (256)
#define s1ap_maxnoofTACs (256)
#define s1ap_maxNrOfErrors (256)
#define s1ap_maxnoofBPLMNs (6)
#define s1ap_maxnoofPLMNsPerMME (32)
#define s1ap_maxnoofEPLMNs (15)
#define s1ap_maxnoofEPLMNsPlusOne (16)
#define s1ap_maxnoofForbLACs (4096)
#define s1ap_maxnoofForbTACs (4096)
#define s1ap_maxNrOfIndividualS1ConnectionsToReset (256)
#define s1ap_maxnoofCells (16)
#define s1ap_maxnoofTAIforWarning (65535)
#define s1ap_maxnoofCellID (65535)
#define s1ap_maxnoofEmergencyAreaID (65535)
#define s1ap_maxnoofCellinTAI (65535)
#define s1ap_maxnoofCellinEAI (65535)
#define s1ap_maxnoofeNBX2TLAs (2)
#define s1ap_maxnoofeNBX2ExtTLAs (16)
#define s1ap_maxnoofeNBX2GTPTLAs (16)
#define s1ap_maxnoofRATs (8)
#define s1ap_maxnoofGroupIDs (65535)
#define s1ap_maxnoofMMECs (256)
#define s1ap_maxnoofCellIDforMDT (32)
#define s1ap_maxnoofTAforMDT (8)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
